import { FormDesign } from '../types/formBuilder';

// --- Template Categories ---
export const templateCategories = [
  {
    name: 'Hardware',
    description: 'Request new hardware or report issues.',
    icon: 'computer-desktop',
    color: '#3b82f6', // blue-500
    sort_order: 1,
    is_active: true,
    // tenant_id will be set during provisioning
    // id will be generated by the database
  },
  {
    name: 'Software',
    description: 'Request software installation or licenses.',
    icon: 'cog',
    color: '#10b981', // emerald-500
    sort_order: 2,
    is_active: true,
  },
  {
    name: 'Access Requests',
    description: 'Request access to systems, applications, or resources.',
    icon: 'shield-check',
    color: '#f97316', // orange-500
    sort_order: 3,
    is_active: true,
  },
  {
    name: 'General Support',
    description: 'General IT support requests.',
    icon: 'question-mark-circle',
    color: '#6b7280', // gray-500
    sort_order: 4,
    is_active: true,
  },
];

// --- Template Services and Forms ---
// We'll define services and their associated forms together.
// The actual category_id will be linked during the provisioning process.

// Structure to hold service and its form design
interface TemplateServiceWithForm {
  service: {
    name: string;
    description: string | null;
    icon: string | null;
    is_active: boolean;
    sort_order: number;
    categoryName: string; // Used to link to the correct category during provisioning
    // tenant_id and category_id will be set during provisioning
  };
  formDesign: FormDesign | null; // Form structure
}

export const templateServices: TemplateServiceWithForm[] = [
  // Hardware Category
  {
    service: {
      name: 'New Laptop Request',
      description: 'Request a new company laptop.',
      icon: 'computer-desktop',
      is_active: true,
      sort_order: 1,
      categoryName: 'Hardware',
    },
    formDesign: {
      sections: [
        {
          id: 'section_details',
          title: 'Request Details',
          fieldIds: ['field_justification', 'field_model_preference', 'field_accessories'],
        },
      ],
      fields: {
        field_justification: {
          id: 'field_justification',
          label: 'Business Justification',
          type: 'textarea',
          required: true,
          options: { placeholder: 'Explain why this laptop is needed' },
          width: 'full',
        },
        field_model_preference: {
          id: 'field_model_preference',
          label: 'Model Preference (Optional)',
          type: 'select',
          required: false,
          options: {
            items: [
              { value: 'standard', label: 'Standard Model' },
              { value: 'performance', label: 'Performance Model' },
              { value: 'macbook', label: 'MacBook' },
            ],
          },
          width: 'full',
        },
        field_accessories: {
          id: 'field_accessories',
          label: 'Required Accessories',
          type: 'checkbox-group',
          required: false,
          options: {
            items: [
              { value: 'docking_station', label: 'Docking Station' },
              { value: 'monitor', label: 'External Monitor' },
              { value: 'keyboard_mouse', label: 'Keyboard & Mouse Set' },
            ],
          },
          width: 'full',
        },
      },
      routing: [],
    },
  },

  // Software Category
  {
    service: {
      name: 'Software Installation Request',
      description: 'Request installation of approved software.',
      icon: 'cog',
      is_active: true,
      sort_order: 1,
      categoryName: 'Software',
    },
    formDesign: {
      sections: [
        {
          id: 'section_software_details',
          title: 'Software Details',
          fieldIds: ['field_software_name', 'field_license_needed', 'field_license_key', 'field_justification_sw'],
        },
      ],
      fields: {
        field_software_name: {
          id: 'field_software_name',
          label: 'Software Name',
          type: 'text',
          required: true,
          options: { placeholder: 'e.g., Adobe Photoshop, Microsoft Project' },
          width: 'full',
        },
        field_license_needed: {
          id: 'field_license_needed',
          label: 'Do you require a new license?',
          type: 'radio-group',
          required: true,
          options: {
            items: [
              { value: 'yes', label: 'Yes' },
              { value: 'no', label: 'No (I have a license)' },
            ],
          },
          width: 'full',
        },
        field_license_key: {
          id: 'field_license_key',
          label: 'License Key (if applicable)',
          type: 'text',
          required: false,
          options: { placeholder: 'Enter your license key if you have one' },
          width: 'full',
        },
        field_justification_sw: {
          id: 'field_justification_sw',
          label: 'Reason for Request',
          type: 'textarea',
          required: true,
          options: { placeholder: 'Explain why you need this software' },
          width: 'full',
        },
      },
      routing: [
        // Conditional logic: Show license key field only if license is NOT needed
        {
          conditions: [{
            fieldId: 'field_license_needed',
            operator: 'is',
            value: 'no',
          }],
          actions: [
            { targetId: 'field_license_key', type: 'show' }
          ],
        },
        // Hide license key field otherwise (default)
         {
          conditions: [{
            fieldId: 'field_license_needed',
            operator: 'isNot',
            value: 'no',
          }],
          actions: [
            { targetId: 'field_license_key', type: 'hide' }
          ],
        },
      ],
    },
  },

  // Access Requests Category
  {
    service: {
      name: 'Password Reset',
      description: 'Request a password reset for an application or system.',
      icon: 'shield-check',
      is_active: true,
      sort_order: 1,
      categoryName: 'Access Requests',
    },
    formDesign: {
      sections: [
        {
          id: 'section_reset_details',
          title: 'Password Reset Details',
          fieldIds: ['field_application_name', 'field_username'],
        },
      ],
      fields: {
        field_application_name: {
          id: 'field_application_name',
          label: 'Application/System Name',
          type: 'text',
          required: true,
          options: { placeholder: 'e.g., VPN, HR Portal, Email' },
          width: 'full',
        },
        field_username: {
          id: 'field_username',
          label: 'Your Username for this System',
          type: 'text',
          required: true,
          width: 'full',
        },
      },
      routing: [],
    },
  },

  // General Support Category
  {
    service: {
      name: 'General IT Support Request',
      description: 'Submit a general IT support issue or question.',
      icon: 'question-mark-circle',
      is_active: true,
      sort_order: 1,
      categoryName: 'General Support',
    },
    formDesign: {
      sections: [
        {
          id: 'section_issue_details',
          title: 'Issue Details',
          fieldIds: ['field_subject', 'field_description', 'field_urgency'],
        },
      ],
      fields: {
        field_subject: {
          id: 'field_subject',
          label: 'Subject',
          type: 'text',
          required: true,
          options: { placeholder: 'Brief summary of the issue' },
          width: 'full',
        },
        field_description: {
          id: 'field_description',
          label: 'Detailed Description',
          type: 'textarea',
          required: true,
          options: { placeholder: 'Please provide as much detail as possible, including error messages or steps to reproduce.' },
          width: 'full',
        },
        field_urgency: {
          id: 'field_urgency',
          label: 'Urgency',
          type: 'select',
          required: true,
          options: {
            items: [
              { value: 'low', label: 'Low' },
              { value: 'medium', label: 'Medium' },
              { value: 'high', label: 'High' },
            ],
          },
          width: 'full',
        },
      },
      routing: [],
    },
  },
];
